name: CI

on:
  push:
    branches:
      - jbe/improved_ci
#  pull_request:
#  workflow_dispatch:

jobs:
  apple-compat:
    runs-on: macos-12
    strategy:
      matrix:
        destination:
          - platform=iOS Simulator,OS=16.0,name=iPhone 14
          - platform=macOS,arch=x86_64
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app
    steps:
      - name: Setup Environment
        run: |
          echo "AWS_SDK_REF_TO_BUILD=$GITHUB_REF_NAME" >> $GITHUB_ENV
          echo "AWS_SDK_XCODEBUILD_DESTINATION=${{ matrix.destination }}" >> $GITHUB_ENV
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Set References
        run: ./scripts/steps/set_references.sh
      - name: Install Dependencies
        run: ./scripts/steps/install_dependencies.sh
      - name: Perform Test Codegen
        run: ./scripts/steps/perform_test_codegen.sh
      - name: Post-Codegen Cleanup
        run: ./scripts/steps/post_codegen_cleanup.sh
      - name: Build and Test With xcodebuild
        run: ./scripts/steps/build_and_test_with_xcodebuild.sh
  linux-compat:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - jammy
          - amazonlinux2
    container:
      image: swift:5.7-${{ matrix.os }}
    steps:
      - name: Install openssl
        run: |
          if [ -x "$(command -v apt)" ]; then
            apt-get update && apt-get install -y libssl-dev
          else
            yum install -y openssl-devel
          fi
      - name: Setup Environment
        run: |
          echo "AWS_SDK_REF_TO_BUILD=$GITHUB_REF_NAME" >> $GITHUB_ENV
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 18
      - name: Set References
        run: ./scripts/steps/set_references.sh
      - name: Install Dependencies
        run: ./scripts/steps/install_dependencies.sh
      - name: Perform Test Codegen
        run: ./scripts/steps/perform_test_codegen.sh
      - name: Post-Codegen Cleanup
        run: ./scripts/steps/post_codegen_cleanup.sh
      - name: Build and Test With Swift CLI
        run: ./scripts/steps/build_and_test_with_swift_cli.sh
