name: Generate Documentation

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  spm-context:
    runs-on: ubuntu-latest
    outputs:
      package-dump: ${{ steps.dump-package.outputs.package-dump }}
    steps:
      - uses: swift-actions/setup-swift@v1.21.0
        with:
          swift-version: "5.7"
      - uses: actions/checkout@v3.2.0
      # We don't use a cache here, because SPM doesn't resolve dependencies when dumping packages.
      - name: Dump package
        id: dump-package
        run: |
          delimiter="$(openssl rand -hex 8)"
          echo "package-dump<<${delimiter}" >> "${GITHUB_OUTPUT}"
          swift package dump-package >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
  generate-docs:
    needs:
      - spm-context
    runs-on: macos-12
    steps:
      - uses: swift-actions/setup-swift@v1.21.0
        id: swift-setup
        with:
          swift-version: "5.7"
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: Generate docs
        run: |
          mkdir -p ./docs/0.7.0/
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target AWSSNS \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path 0.7.0/AWSSNS \
            --output-path ./docs/0.7.0/AWSSNS
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target AWSS3 \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path 0.7.0/AWSS3 \
            --output-path ./docs/0.7.0/AWSS3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.CD_API_REFS_PUBLISH_ROLE_ARN }}
          aws-region: us-east-1
      - name: Upload to S3
        run: |
          aws s3 sync ./docs/0.7.0 S3://${{ secrets.CD_API_REFS_BUCKET_NAME }} --delete